export const Users = [
  {
    id: 1,
    name: "Nguyễn Vân",
    username: "Nguyễn Vân",
    email: "van@logan.tv",
    profilePicture: "/assets/person/person1.jpg",
   
  },
  {
    id: 2,
    name: "Lê Anh",
    username: "Lê Anh",
    email: "Blanche@randy.biz",
    profilePicture: "/assets/person/person2.jpg",

  },
  {
    id: 3,
    name: "Huyền Châu",
    username: "Huyền Châu",
    email: "Brenna@rosamond.me",
    profilePicture: "/assets/person/person3.jpg",
   
  },
  {
    id: 4,
    name: "Tuấn Kiệt",
    username: "Tuấn Kiệt",
    email: "Calantha@dana.io",
    profilePicture: "/assets/person/person4.jpg",
  
  },
  {
    id: 5,
    name: "Tuấn Anh",
    username: "Tuấn Anh",
    email: "Ceridweng@karina.biz",
    profilePicture: "/assets/person/person5.jpg",
   
  },
];


//chat
export const Chats = [
  {
    id: 1,
    name: "Nguyễn Vân",
    username: "Nguyễn Vân",
    message: "Xin chào",
    profilePicture: "/assets/person/person1.jpg",
    time : "1 phút",
    ring : true,
    watched: true,
  },
  {
    id: 2,
    name: "Lê Anh",
    username: "Lê Anh",
    message: "Cho tôi hỏi cái này",
    profilePicture: "/assets/person/person2.jpg",
    time : "40 phút",
    ring : false,
    watched: true,
    
  },
  {
    id: 3,
    name: "Huyền Châu",
    username: "Huyền Châu",
    message: "Dạo này bạn khoẻ không",
    profilePicture: "/assets/person/person3.jpg",
    time : "10 phút",
    ring : true,
    watched: false,
  },
  {
    id: 4,
    name: "Tuấn Kiệt",
    username: "Tuấn Kiệt",
    message: "Cho tôi hỏi cái này",
    profilePicture: "/assets/person/person4.jpg",
    time : "1 ngày",
    ring : true,
    watched: true,
  },
  {
    id: 5,
    name: "Tuấn Anh",
    username: "Tuấn Anh",
    message: "Xin chào",
    profilePicture: "/assets/person/person5.jpg",
    time : "31 phút",
    ring : false,
    watched: false,
  },
];



export const Usersonline = [
  {
    id: 1,
    name: "Hà Trường Huy",
    username: "Hà Trường Huy",
    email: "Sincere@april.biz",
    profilePicture: "/assets/person/friend1.jpg",
  },
  {
    id: 2,
    name: "Phạm Thị Như Ý",
    username: "Phạm Thị Như Ý",
    email: "Shanna@melissa.tv",
    profilePicture: "/assets/person/friend2.jpg",
  },
  {
    id: 3,
    name: "Trịnh Minh Hậu",
    username: "Trịnh Minh Hậu",
    email: "Nathan@yesenia.net",
    profilePicture: "/assets/person/friend3.jpg",
  },
  {
    id: 4,
    name: "Tường Vy",
    username: "Tường Vy",
    email: "Julianne.OConner@kory.org",
    profilePicture: "/assets/person/friend4.jpg",
  },
  {
    id: 5,
    name: "Thục Trâm",
    username: "Thục Trâm",
    email: "Lucio_Hettinger@annie.ca",
    profilePicture: "/assets/person/friend5.jpg",
  },
  {
    id: 6,
    name: "Tấn Thành",
    username: "Tấn Thành",
    email: "Karley_Dach@jasper.info",
    profilePicture: "/assets/person/friend6.jpg",
  },
  {
    id: 7,
    name: "Hiền Nhi",
    username: "Hiền Nhi",
    email: "Telly.Hoeger@billy.biz",
    profilePicture: "/assets/person/friend7.jpg",
  },
  {
    id: 8,
    name: "Duy Võ",
    username: "Duy Võ",
    email: "Sherwood@rosamond.me",
    profilePicture: "/assets/person/friend8.jpg",
  },
  {
    id: 9,
    name: "Hữu An",
    username: "Hữu An",
    email: "Chaim_McDermott@dana.io",
    profilePicture: "/assets/person/friend9.jpg",
  },
  {
    id: 10,
    name: "Vũ Quốc",
    username: "Vũ Quốc",
    email: "Rey.Padberg@karina.biz",
    profilePicture: "/assets/person/friend10.jpg",
  },
  {
    id: 11,
    name: "Nguyễn Phụng",
    username: "Nguyễn Phụng",
    email: "Rey.Padberg@karina.biz",
    profilePicture: "/assets/person/friend11.jpg",
  },
];

export const Posts = [
  {
    userId: 3,
    id: 1,
    title: "Không nghĩ thêm gì về Vợ nhặt nữa, tập trung cho môn thi buổi chiều nhé các sĩ tử",
    body: "Không nghĩ thêm gì về Vợ nhặt nữa, tập trung cho môn thi buổi chiều nhé các sĩ tử",
    photo: "/assets/posts/post1.jpg",
    date: "5 phút trước",
    like: "100",
    comment: "70",
  },
  {
    userId: 2,
    id: 2,
    title: "Mình cụ cân tất",
    body: "Mình cụ cân tất.",
    photo: "/assets/posts/post2.jpg",
    date: "23 phút tước",
    like: "480",
    comment: "112",
  },
  {
    userId: 1,
    id: 3,
    title: "Giá vé concert BLACKPINK thế này mà còn không đi thì cạn lời",
    body: "Giá vé concert BLACKPINK thế này mà còn không đi thì cạn lời",
    photo: "/assets/posts/post3.jpg",
    date: "10 giờ trước",
    like: "10",
    comment: "30",
  },

  {
    userId: 3,
    id: 4,
    title: "Robin 😊😂",
    body: "Robin 😊😂",
    photo: "/assets/posts/post4.jpg",
    date: "23 giờ trước",
    like: "10",
    comment: "30",
  },
  {
    userId: 4,
    id: 5,
    title: "Theo trend gần đây, phiên bản Anemo Boys 😇😇😇",
    body: "Theo trend gần đây, phiên bản Anemo Boys 😇😇😇    ",
    photo: "/assets/posts/post5.jpg",
    date: "2 ngày trước",
    like: "1,2k",
    comment: "590",
  },
  {
    userId: 2,
    id: 6,
    title: "Tôi: Coi phim để giảm bớt áp lực, tạm thời quên đi gánh nặng cơm, áo, gạo, tiền trong cuộc sống.",
    body: "Tôi: Coi phim để giảm bớt áp lực, tạm thời quên đi gánh nặng cơm, áo, gạo, tiền trong cuộc sống.",
    photo: "/assets/posts/post6.jpg",
    date: "2 ngày trước",
    like: "130",
    comment: "31",
  },
  {
    userId: 1,
    id: 7,
    title: "✍️✍️",
    body: "✍️✍️",
    photo: "/assets/posts/post7.jpg",
    date: "2 tuần trước",
    like: "10",
    comment: "30",
  },
  {
    userId: 4,
    id: 8,
    title: "Muzan rén liền 😅",
    body: "Muzan rén liền 😅",
    photo: "/assets/posts/post8.jpg",
    date: "3 tuần trước",
    like: "780",
    comment: "412",
  },
  {
    userId: 1,
    id: 9,
    title: "Sương sương tháng 7 🥰",
    body: "Sương sương tháng 7 🥰",
    photo: "/assets/posts/post9.jpg",
    date: "2 months ago",
    like: "10",
    comment: "3",
  },
  {
    userId: 2,
    id: 10,
    title: "Mẫu người đàn ông các chị em mong chờ đã xuất hiện :)))",
    body: "Mẫu người đàn ông các chị em mong chờ đã xuất hiện :)))",
    photo: "/assets/posts/post10.jpg",
    date: "4 months ago",
    like: "86",
    comment: "12",
  },
  {
    userId: 3,
    id: 11,
    title: "Bully Maguire ở",
    body: "Bully Maguire ở",
    photo: "/assets/posts/post11.jpg",
    date: "1 tháng trước",
    like: "1000",
    comment: "340",
  },
  {
    userId: 1,
    id: 12,
    title: "Đi Fahasa lấy poster IPM về chưa kịp hí hửng thì nghe tin BlackPink về Việt Nam, shock quá bóp gãy cmn poster đang cầm trên tay luôn 🥲 còn nỗi đau nào hơn nỗi đau này 🤡",
    body: "Đi Fahasa lấy poster IPM về chưa kịp hí hửng thì nghe tin BlackPink về Việt Nam, shock quá bóp gãy cmn poster đang cầm trên tay luôn 🥲 còn nỗi đau nào hơn nỗi đau này 🤡",
    photo: "/assets/posts/post12.jpg",
    date: "1 tháng trước",
    like: "760",
    comment: "500",
  },
  {
    userId: 2,
    id: 13,
    title: "Đi làm mà sợ mấy má nhân viên cũ bắt nạt kiểu:",
    body: "Đi làm mà sợ mấy má nhân viên cũ bắt nạt kiểu:",
    photo: "/assets/posts/post13.jpg",
    date: "10 giờ trước",
    like: "10",
    comment: "30",
  },
  {
    userId: 4,
    id: 14,
    title: "Không ngờ chứ gì",
    body: "Không ngờ chứ gì",
    photo: "/assets/posts/post14.jpg",
    date: "1 tháng trước",
    like: "48",
    comment: "7",
  },
];
